from django.contrib.auth import get_user_model
from rest_framework.serializers import HyperlinkedIdentityField, ModelSerializer
from rest_framework_simplejwt.serializers import TokenObtainPairSerializer

User = get_user_model()


class CustomTokenObtainPairSerializer(TokenObtainPairSerializer):
    """
    customize the claims in tokens generated by the TokenObtainPairView
    """

    @classmethod
    def get_token(cls, user):
        token = super().get_token(user)
        # # Add custom claims
        token["username"] = user.username

        return token


class UserSerializer(ModelSerializer):
    user_detail_url = HyperlinkedIdentityField(
        view_name="user-detail", read_only=True, lookup_field="pk"
    )

    class Meta:
        model = User
        exclude = (
            "groups",
            "user_permissions",
            "password",
        )
